### ISSUE TITLE
packup & DESCRIPTION

### ISSUE THREAD

**Issue by maelle** [MilesMcBain/packup#6]
Hi @MilesMcBain , alphabetical order expert! I forgot if we discussed this before, could packup help order dependencies under each field in DESCRIPTION? Or should it be another package wrapping [`desc`](https://github.com/r-lib/desc)? Or maybe `desc` already has alphabetical order 🤔 https://github.com/r-lib/desc#dependencies

Cc @aedobbyn

**Comment by maelle** [comment]
I _think_ that currently the order is not alphabetical cf

https://github.com/r-lib/desc/blob/f6f0753a86dddd89a34bdae0a52eee532d66333b/R/deps.R

(which is [what `usethis` uses](https://github.com/r-lib/usethis/blob/4fb556788d2588facaaa8560242d2c83f2261d6e/R/helpers.R))

Miles, also feel free to close if this discussion is out of scope for `packup` 👼

**Comment by MilesMcBain** [comment]
I like this idea but I think it is a different tool. Packup is about Rmd files.

So do you want to alphabetise everything? or just suggests, depends... etc?

**Comment by maelle** [comment]
Just packages inside each field (suggests, depends, imports). Should I close this issue?

**Comment by MilesMcBain** [comment]
Yes, let's close this, outside the scope of packup I think.
